### PR TITLE
new handler, changed surveys format. Need to be tested / debugged by …

### PR DESCRIPTION
**Pull request by CarlosHL**
Need to be tested by someone else.

### CODE REVIEW

**Comment by Brady76** [comment]
Make sure that you don't edit all.js, go find the specific component in the directory and edit it there. All.js is the product of the concatenation of several other files by the gulp.

**Comment by CarlosHL** [comment]
Does gulp made the concatenation in running time? I have changed all.js because it was the file with the hardcoded surveys and it was easier to test.

**Comment by Brady76** [comment]
Hey @CarlosHL did you still want this opened?

**Comment by CarlosHL** [comment]
Closing.

**Pull request closed without merging**
