### PR TITLE
Profile: pending groups

### PR DESCRIPTION
**Pull request by sungbae**

### CODE REVIEW

**Comment by sungbae** [comment]
Everything is working fine but make test failed for 1 test. Maybe it's because I removed the first entry of list members. Which is needed for this PR to work. 

edit: Yup, it's because of line 33 in group_api_handler.py. Can I remove this specific line of test? @untra 

FAIL: test_api_group (test_group_subscribe.TestGroupSubscribe)
Traceback (most recent call last):

  File "/usr/local/lib/python3.4/dist-packages/tornado/testing.py", line 120, in **call**
    result = self.orig_method(_args, *_kwargs)

  File "/home/user/github/scq/test/test_group_subscribe.py", line 45, in test_api_group
    self.assertEqual(response2.code, 200, str(response2.error))

AssertionError: 500 != 200 : HTTP 500: Internal Server Error

Ran 37 tests in 3.279s

FAILED (failures=1)

**Comment by nicot** [comment]
This looks good, but that test should pass one way or another. Were you able to figure out the right way to do it?

**Comment by sungbae** [comment]
Alright I fixed the test. Can I merge soon?

**Comment by nicot** [comment]
Yes, go ahead and merge it.

**Pull request merged**
