### PR TITLE
coordinating user cookie with user value

### PR DESCRIPTION
**Pull request by untra**
Addresses #130 

Note that when using `bootstrap_data`, you will still need to refresh the page. This is because bootstrap_data does work directly with the database and backend, and is 100% agnostic to the frontend and cookie values. Fixing that would be wwaayy more code than its worth.

However API calls will now refresh the `current_user` cookie when decorated with the `@refresh_user_cookie_callback` decorator

### CODE REVIEW

**Comment by sungbae** [comment]
God bless, Sam.

**Comment by sungbae** [comment]
I think it looks good, are you ready to merge? Give me a thumbs up if so @untra 

edit: wait actually, we may want to remove major/minors, departments, courses/courses_taught

**Comment by untra** [comment]
@sungbae do you want to remove them? I'm not sure what users look like strictly right now. That would be a quick PR for you, with whatever other cleanup you want to get done.

:+1:

**Comment by sungbae** [comment]
No problem, I'll merge this and clean up in my branch. Let me know if there are any other changes you want to make in this pr. I'll merge it in like 20min, I'm going to take a quick break. @untra

**Pull request merged**
